# spell-checker:ignore (utils) dprint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno: ['canary', 'v1.x', '1.9.0', '1.8.0']
    name: Test with Deno ${{ matrix.deno }}

    steps:
      - uses: actions/checkout@v2

      - name: Setup Deno
        uses: denoland/setup-deno@a33d97bf8b725ee4580bc140380cfe4120615fef
        with:
          deno-version: ${{ matrix.deno }}

      - name: Print deno version
        run: deno --version

      - name: Check format
        uses: dprint/check@v1.3

      - name: Run tests
        run: deno test
